# Generated by Django 5.0.3 on 2024-03-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_Posts_cat_UserAcc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='post/imgs/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='post52', max_length=128, null=True),
        ),
    ]
