# Generated by Django 5.0.3 on 2024-03-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_Post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='post18', max_length=128, null=True),
        ),
    ]
